// Generated by CoffeeScript 1.6.3
var escapeInvalidXmlChars, failureMessage, formatErrors, fs, path;

path = require('path');

fs = require('fs');

escapeInvalidXmlChars = function(str) {
  return str.replace(/</g, "&lt;").replace(/\>/g, "&gt;").replace(/\"/g, "&quot;").replace(/\'/g, "&apos;").replace(/\&/g, "&amp;");
};

failureMessage = function(error) {
  return escapeInvalidXmlChars("" + error.line + ":" + error.character + ": " + error.reason);
};

formatErrors = function(errors) {
  var error, fileName, message, numTests, output, _i, _len;
  numTests = errors.length;
  output = [];
  output.push("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>");
  output.push("<testsuite name=\"coffeejshint\" errors=\"0\" tests=\"" + numTests + "\" failures=\"" + numTests + "\">");
  if (numTests === 0) {
    output.push("\t<testcase name=\"coffeejshint\" />");
  }
  for (_i = 0, _len = errors.length; _i < _len; _i++) {
    error = errors[_i];
    fileName = escapeInvalidXmlChars(error.path);
    message = failureMessage(error);
    output.push("\t<testcase className=\"" + fileName + "\" name=\"" + message + "\">");
    output.push("\t\t<failure message=\"" + message + "\" />");
    output.push("\t</testcase>");
  }
  output.push("</testsuite>");
  return output;
};

module.exports = function(destination, errors) {
  var output;
  output = formatErrors(errors);
  return fs.writeFileSync(destination, output.join("\n"));
};
